/* hierarchy.svelte.ts generated by Svelte v5.38.7 */
import * as $ from 'svelte/internal/client';
import { getContext, setContext } from "svelte";
import { childIndices, depth, parentIndex, yogaNodes } from '../core/state/engine.svelte.js';

export function setupComponent(index, canHaveChildren = false) {
	const parentIdx = getContext("parentIndex");

	if ($.strict_equals(parentIdx, undefined, false)) {
		parentIndex[index] = parentIdx;

		if (!childIndices[parentIdx]) {
			childIndices[parentIdx] = [];
		}

		childIndices[parentIdx].push(index);

		const parentDepth = depth[parentIdx];

		if ($.strict_equals(parentDepth, undefined)) {
			throw new Error("Parent depth is undefined");
		}

		depth[index] = parentDepth + 1;

		const childNode = yogaNodes[index];
		const parentNode = yogaNodes[parentIdx];

		if (childNode && parentNode) {
			parentNode.insertChild(childNode, parentNode.getChildCount());
		}
	} else {
		parentIndex[index] = -1;
		depth[index] = 0;
	}

	if (canHaveChildren) {
		setContext("parentIndex", index);
	}
}

export function cleanupComponent(index) {
	const childNode = yogaNodes[index];

	if (childNode) {
		const parentNode = childNode.getParent();

		if (parentNode) {
			parentNode.removeChild(childNode);
		}
	}

	const parentIdx = parentIndex[index];

	if (parentIdx && parentIdx >= 0 && childIndices[parentIdx]) {
		const children = childIndices[parentIdx];
		const childIndex = children.indexOf(index);

		if (childIndex >= 0) {
			children.splice(childIndex, 1);
		}
	}

	childIndices[index] = [];
}