/* currentTheme.svelte.ts generated by Svelte v5.38.7 */
import * as $ from 'svelte/internal/client';
import { getThemeRegistry } from './theme-utils.svelte.js';

const initialTheme = {
	name: "Default",
	description: "Default theme",
	author: "RLabs Inc.",
	version: "1.0.0",

	colors: {
		primary: "blue",
		secondary: "cyan",
		background: null,
		foreground: null,
		success: "green",
		error: "red",
		warning: "yellow",
		info: "blue"
	},

	derived: { surfaceColor: null, mutedText: null }
};

let currentTheme = $.tag($.state($.proxy(initialTheme)), 'currentTheme');

export function applyThemeToProps(elementType, props) {
	if (!$.get(currentTheme)) {
		console.warn("applyThemeToProps: Theme is undefined, returning original props");

		return { ...props };
	}

	const result = { ...props };

	switch (elementType.toLowerCase()) {
		case "box":
			if ($.strict_equals($.get(currentTheme).colors.background, null, false)) {
				result.bg = $.get(currentTheme).colors.background;
			}
			if ($.strict_equals($.get(currentTheme).colors.foreground, null, false)) {
				result.fg = $.get(currentTheme).colors.foreground;
			}
			break;

		case "text":
			if ($.strict_equals($.get(currentTheme).colors.foreground, null, false)) {
				result.fg = $.get(currentTheme).colors.foreground;
			}
			break;

		case "list":
			if ($.strict_equals($.get(currentTheme).colors.background, null, false)) {
				result.bg = $.get(currentTheme).colors.background;
			}
			if ($.strict_equals($.get(currentTheme).colors.foreground, null, false)) {
				result.fg = $.get(currentTheme).colors.foreground;
			}
			break;

		case "input":

		case "textarea":
			if ($.strict_equals($.get(currentTheme).colors.background, null, false)) {
				result.bg = $.get(currentTheme).colors.background;
			}
			if ($.strict_equals($.get(currentTheme).colors.foreground, null, false)) {
				result.fg = $.get(currentTheme).colors.foreground;
			}
			break;

		case "select":
			if ($.strict_equals($.get(currentTheme).colors.background, null, false)) {
				result.bg = $.get(currentTheme).colors.background;
			}
			if ($.strict_equals($.get(currentTheme).colors.foreground, null, false)) {
				result.fg = $.get(currentTheme).colors.foreground;
			}
			result.tags = true;
			result.style = result.style || {};
			if (props.isFocused || props.focused) {
				result.style.border = result.style.border || {};
				result.style.border.fg = $.get(currentTheme).colors.primary || "blue";
			}
			if (props.open) {
				result.style.selected = result.style.selected || {};
				result.style.selected.bg = $.get(currentTheme).colors.primary || "blue";
				result.style.selected.fg = $.get(currentTheme).colors.foreground || "white";
			}
			break;

		case "checkbox":
			if ($.strict_equals($.get(currentTheme).colors.foreground, null, false)) {
				result.fg = $.get(currentTheme).colors.foreground;
			}
			result.tags = true;
			result.style = result.style || {};
			if (props.disabled) {
				result.style.fg = "gray";
			} else if (props.isFocused || props.focused) {
				result.style.fg = $.get(currentTheme).colors.primary || "blue";
			}
			break;
	}

	return result;
}

export function getCurrentTheme() {
	const themeRegistry = getThemeRegistry();

	function getColors() {
		return $.get(currentTheme).colors;
	}

	function getThemeInfo() {
		return {
			name: $.get(currentTheme).name,
			description: $.get(currentTheme).description,
			author: $.get(currentTheme).author,
			version: $.get(currentTheme).version
		};
	}

	function setTheme(theme) {
		if ($.strict_equals(typeof theme, "string")) {
			const foundTheme = themeRegistry().getTheme(theme.toLowerCase());

			if (foundTheme) {
				$.set(currentTheme, foundTheme, true);

				return true;
			}

			return false;
		} else {
			$.set(currentTheme, theme, true);

			return true;
		}
	}

	function getAvailableThemeNames() {
		return themeRegistry().getAvailableThemes();
	}

	function loadThemeFromFile(filePath) {
		const theme = themeRegistry().loadTheme(filePath);

		if (theme) {
			themeRegistry().registerTheme(theme);

			return theme;
		}

		return null;
	}

	function registerCustomTheme(theme) {
		themeRegistry().registerTheme(theme);
	}

	function createCustomTheme(name, colors) {
		const theme = themeRegistry().createTheme(name, colors);

		themeRegistry().registerTheme(theme);

		return theme;
	}

	return () => ({
		currentTheme: $.get(currentTheme),
		getColors,
		getThemeInfo,
		setTheme,
		getAvailableThemeNames,
		loadThemeFromFile,
		registerCustomTheme,
		createCustomTheme,
		applyThemeToProps
	});
}