/* theme-utils.svelte.ts generated by Svelte v5.38.7 */
import * as $ from 'svelte/internal/client';
import * as yaml from "js-yaml";

let themeRegistry = $.tag($.state($.proxy(new Map())), 'themeRegistry');
let fs = null;
let path = null;
let BUILT_IN_THEMES_DIR = "";
let CUSTOM_THEMES_DIR = "";
const isNodeEnv = $.strict_equals(typeof process, "undefined", false) && $.equals(process.versions, null, false) && $.equals(process.versions.node, null, false);

let themesPaths = $.tag(
	$.derived(() => {
		if (isNodeEnv) {
			try {
				fs = require("fs");
				path = require("path");
				BUILT_IN_THEMES_DIR = path.resolve(process.cwd(), "themes/built-in");
				CUSTOM_THEMES_DIR = path.resolve(process.cwd(), "themes/custom");
			} catch(error) {
				console.warn(...$.log_if_contains_state('warn', "Error checking theme directories:", error));
			}

			return {
				builtIn: fs ? fs.readdirSync(BUILT_IN_THEMES_DIR) : [],
				custom: fs ? fs.readdirSync(CUSTOM_THEMES_DIR) : []
			};
		}
	}),
	'themesPaths'
);

export function getThemeRegistry() {
	function refreshThemes() {
		initializeThemes();
	}

	function registerTheme(theme) {
		const updatedRegistry = new Map($.get(themeRegistry));

		updatedRegistry.set(theme.name.toLowerCase(), theme);
		$.set(themeRegistry, updatedRegistry, true);
	}

	function getTheme(name) {
		return $.get(themeRegistry).get(name.toLowerCase());
	}

	function getAvailableThemes() {
		return Array.from($.get(themeRegistry).keys());
	}

	function loadTheme(filePath) {
		if (!isNodeEnv || !fs) {
			console.warn("Theme loading requires Node.js environment");

			return null;
		}

		try {
			const fileContent = fs.readFileSync(filePath, "utf8");
			const themeData = yaml.load(fileContent);

			if (!themeData.name || !themeData.colors) {
				console.error("Invalid theme format: missing required properties");

				return null;
			}

			return themeData;
		} catch(error) {
			console.error(`Error loading theme: ${error}`);

			return null;
		}
	}

	function loadThemesFromDirectory(directoryPath) {
		if (!isNodeEnv || !fs || !path || !directoryPath) return;

		try {
			if (fs.existsSync(directoryPath)) {
				const themeFiles = fs.readdirSync(directoryPath).filter((file) => file.endsWith(".yaml") || file.endsWith(".yml"));

				themeFiles.forEach((file) => {
					try {
						const theme = loadTheme(path.join(directoryPath, file));

						if (theme) {
							registerTheme(theme);
						}
					} catch(error) {
						console.warn(...$.log_if_contains_state('warn', `Failed to load theme ${file}:`, error));
					}
				});
			}
		} catch(error) {
			console.warn(...$.log_if_contains_state('warn', `Failed to load themes from ${directoryPath}:`, error));
		}
	}

	function initializeThemes() {
		$.set(themeRegistry, new Map(), true);
		loadThemesFromDirectory($.get(themesPaths)?.builtIn);
		loadThemesFromDirectory($.get(themesPaths)?.custom);
	}

	function getThemeFiles() {
		const result = { builtIn: [], custom: [] };

		if (!isNodeEnv || !fs || !path) {
			console.warn("Theme file operations require Node.js environment");

			return result;
		}

		try {
			if (fs.existsSync($.get(themesPaths)?.builtIn)) {
				result.builtIn = fs.readdirSync($.get(themesPaths)?.builtIn).filter((file) => file.endsWith(".yaml") || file.endsWith(".yml")).map((file) => path.join($.get(themesPaths)?.builtIn, file));
			}
		} catch(error) {
			console.warn(...$.log_if_contains_state('warn', "Failed to read built-in theme directory:", error));
		}

		try {
			if (fs.existsSync($.get(themesPaths)?.custom)) {
				result.custom = fs.readdirSync($.get(themesPaths)?.custom).filter((file) => file.endsWith(".yaml") || file.endsWith(".yml")).map((file) => path.join($.get(themesPaths)?.custom, file));
			}
		} catch(error) {
			console.warn(...$.log_if_contains_state('warn', "Failed to read custom theme directory:", error));
		}

		return result;
	}

	function createTheme(name, colors) {
		return {
			name,
			description: `Custom theme: ${name}`,
			author: "User",
			version: "1.0.0",

			colors: {
				primary: colors.primary,
				secondary: colors.primary,
				background: colors.background,
				foreground: colors.foreground,
				success: "green",
				warning: "yellow",
				error: "red",
				info: "blue"
			}
		};
	}

	return () => ({
		themeRegistry: $.get(themeRegistry),
		themesPaths: $.get(themesPaths),
		getTheme,
		registerTheme,
		getAvailableThemes,
		getThemeFiles,
		loadTheme,
		createTheme,
		refreshThemes
	});
}