/* theme.svelte.ts generated by Svelte v5.38.7 */
import * as $ from 'svelte/internal/client';
import { parseColor } from '../utils/bun-color.mjs';

const colors = $.tag_proxy(
	$.proxy({
		primary: 4,
		secondary: 5,
		tertiary: 6,
		accent: 3,
		success: 2,
		warning: 3,
		error: 1,
		info: 6,
		text: undefined,
		textMuted: 8,
		textBright: 15,
		background: undefined
	}),
	'colors'
);

const metadata = $.tag_proxy(
	$.proxy({
		name: "default",
		description: "Terminal default colors",
		author: "SvelTUI"
	}),
	'metadata'
);

const themes = {
	default: {
		name: "default",
		description: "Terminal default colors",

		colors: {
			primary: 11,
			secondary: 6,
			tertiary: 5,
			accent: 9,
			success: 2,
			warning: 3,
			error: 1,
			info: 4,
			text: undefined,
			textMuted: 8,
			textBright: 15,
			background: undefined
		}
	},

	dracula: {
		name: "dracula",
		description: "Dracula theme",

		colors: {
			primary: 12424185,
			secondary: 16742854,
			tertiary: 9169405,
			accent: 15858316,
			success: 5307003,
			warning: 15858316,
			error: 16733525,
			info: 9169405,
			text: 16316658,
			textMuted: 6451876,
			textBright: 16777215,
			background: 2632246
		}
	},

	nord: {
		name: "nord",
		description: "Nord theme",

		colors: {
			primary: 8962256,
			secondary: 8495553,
			tertiary: 6193580,
			accent: 13666160,
			success: 10731148,
			warning: 15453067,
			error: 12542314,
			info: 8962256,
			text: 14212841,
			textMuted: 5002858,
			textBright: 15527924,
			background: 3028032
		}
	},

	monokai: {
		name: "monokai",
		description: "Monokai theme",

		colors: {
			primary: 16328306,
			secondary: 10936878,
			tertiary: 11436543,
			accent: 16619295,
			success: 10936878,
			warning: 16619295,
			error: 16328306,
			info: 6740463,
			text: 16316658,
			textMuted: 7696734,
			textBright: 16777215,
			background: 2566178
		}
	},

	solarized: {
		name: "solarized",
		description: "Solarized Dark theme",

		colors: {
			primary: 2526162,
			secondary: 2793880,
			tertiary: 8755456,
			accent: 13323030,
			success: 8755456,
			warning: 11897088,
			error: 14430767,
			info: 2526162,
			text: 8623254,
			textMuted: 5795445,
			textBright: 9675169,
			background: 11062
		}
	}
};

function setTheme(themeName) {
	if ($.strict_equals(typeof themeName, "string")) {
		const preset = themes[themeName];

		if (!preset) {
			console.error(`Theme '${themeName}' not found`);

			return;
		}

		Object.assign(colors, preset.colors);
		metadata.name = preset.name;
		metadata.description = preset.description;
	} else {
		if (themeName.colors) {
			Object.assign(colors, themeName.colors);
		}

		if (themeName.metadata) {
			Object.assign(metadata, themeName.metadata);
		}
	}
}

export function getTheme() {
	return () => ({
		colors,
		metadata,
		setTheme,
		availableThemes: Object.keys(themes)
	});
}