/* debug-panel.svelte.ts generated by Svelte v5.38.7 */
import * as $ from 'svelte/internal/client';
import { getEngine } from '../core/state/engine.svelte.js';

const engine = getEngine();
let debugVisible = $.tag($.state(false), 'debugVisible');
let lastKey = $.tag($.state(""), 'lastKey');
let lastRawKey = $.tag($.state(""), 'lastRawKey');
let keyHistory = $.tag($.state($.proxy([])), 'keyHistory');
let panelBoxIndex = -1;
let panelTitleIndex = -1;
let panelKeyIndex = -1;
let panelFocusIndex = -1;
let panelStatsIndex = -1;
let panelHistoryIndex = -1;

export function toggleDebugPanel() {
	$.set(debugVisible, !$.get(debugVisible));

	if ($.get(debugVisible)) {
		createDebugPanel();
	} else {
		destroyDebugPanel();
	}
}

export function updateDebugKey(key, raw) {
	$.set(lastKey, key, true);
	$.set(lastRawKey, raw, true);

	const hexRaw = Array.from(raw).map((c) => {
		const code = c.charCodeAt(0);

		return `0x${code.toString(16).padStart(2, "0")}`;
	}).join(" ");

	$.set(keyHistory, [...$.get(keyHistory).slice(-4), `${key} (${hexRaw})`], true);

	if ($.get(debugVisible) && panelKeyIndex >= 0) {
		engine().texts[panelKeyIndex] = `Key: "${key}" | Raw: ${hexRaw} | JSON: ${JSON.stringify(raw)}`;
		engine().texts[panelFocusIndex] = `Focus: ${engine().focus.index} | Focusables: ${engine().focusableCount}`;
		engine().texts[panelStatsIndex] = `Active: ${engine().activeCount} | Visible: ${engine().visibleComponents.length}`;
		engine().texts[panelHistoryIndex] = `History: ${$.get(keyHistory).slice(-3).join(" > ")}`;
	}
}

function createDebugPanel() {
	const width = 60;
	const height = 8;
	const x = engine().terminalSize.width - width - 2;
	const y = 2;
	const boxId = "debug-panel-box";

	panelBoxIndex = engine().allocateIndex(boxId);
	engine().componentType[panelBoxIndex] = 1;
	engine().positions[panelBoxIndex * 4] = x;
	engine().positions[panelBoxIndex * 4 + 1] = y;
	engine().positions[panelBoxIndex * 4 + 2] = width;
	engine().positions[panelBoxIndex * 4 + 3] = height;
	engine().borderStyles[panelBoxIndex] = 2;
	engine().borderColors[panelBoxIndex * 2] = 16711935;
	engine().colors[panelBoxIndex * 2 + 1] = 51;
	engine().visibility[panelBoxIndex] = true;
	engine().zIndex[panelBoxIndex] = 9999;

	const titleId = "debug-panel-title";

	panelTitleIndex = engine().allocateIndex(titleId);
	engine().componentType[panelTitleIndex] = 0;
	engine().positions[panelTitleIndex * 4] = x + 2;
	engine().positions[panelTitleIndex * 4 + 1] = y + 1;
	engine().positions[panelTitleIndex * 4 + 2] = width - 4;
	engine().positions[panelTitleIndex * 4 + 3] = 1;
	engine().texts[panelTitleIndex] = "=== DEBUG PANEL (Ctrl+P to toggle) ===";
	engine().colors[panelTitleIndex * 2] = 65535;
	engine().visibility[panelTitleIndex] = true;
	engine().zIndex[panelTitleIndex] = 1e4;

	const keyId = "debug-panel-key";

	panelKeyIndex = engine().allocateIndex(keyId);
	engine().componentType[panelKeyIndex] = 0;
	engine().positions[panelKeyIndex * 4] = x + 2;
	engine().positions[panelKeyIndex * 4 + 1] = y + 2;
	engine().positions[panelKeyIndex * 4 + 2] = width - 4;
	engine().positions[panelKeyIndex * 4 + 3] = 1;
	engine().texts[panelKeyIndex] = `Key: "${$.get(lastKey)}" | Raw: ${JSON.stringify($.get(lastRawKey))}`;
	engine().colors[panelKeyIndex * 2] = 16776960;
	engine().visibility[panelKeyIndex] = true;
	engine().zIndex[panelKeyIndex] = 1e4;

	const focusId = "debug-panel-focus";

	panelFocusIndex = engine().allocateIndex(focusId);
	engine().componentType[panelFocusIndex] = 0;
	engine().positions[panelFocusIndex * 4] = x + 2;
	engine().positions[panelFocusIndex * 4 + 1] = y + 3;
	engine().positions[panelFocusIndex * 4 + 2] = width - 4;
	engine().positions[panelFocusIndex * 4 + 3] = 1;
	engine().texts[panelFocusIndex] = `Focus: ${engine().focus.index} | Focusables: ${engine().focusableCount}`;
	engine().colors[panelFocusIndex * 2] = 65280;
	engine().visibility[panelFocusIndex] = true;
	engine().zIndex[panelFocusIndex] = 1e4;

	const statsId = "debug-panel-stats";

	panelStatsIndex = engine().allocateIndex(statsId);
	engine().componentType[panelStatsIndex] = 0;
	engine().positions[panelStatsIndex * 4] = x + 2;
	engine().positions[panelStatsIndex * 4 + 1] = y + 4;
	engine().positions[panelStatsIndex * 4 + 2] = width - 4;
	engine().positions[panelStatsIndex * 4 + 3] = 1;
	engine().texts[panelStatsIndex] = `Active: ${engine().activeCount} | Visible: ${engine().visibleComponents.length}`;
	engine().colors[panelStatsIndex * 2] = 8947967;
	engine().visibility[panelStatsIndex] = true;
	engine().zIndex[panelStatsIndex] = 1e4;

	const historyId = "debug-panel-history";

	panelHistoryIndex = engine().allocateIndex(historyId);
	engine().componentType[panelHistoryIndex] = 0;
	engine().positions[panelHistoryIndex * 4] = x + 2;
	engine().positions[panelHistoryIndex * 4 + 1] = y + 5;
	engine().positions[panelHistoryIndex * 4 + 2] = width - 4;
	engine().positions[panelHistoryIndex * 4 + 3] = 1;
	engine().texts[panelHistoryIndex] = `History: ${$.get(keyHistory).slice(-3).join(" > ")}`;
	engine().colors[panelHistoryIndex * 2] = 8421504;
	engine().visibility[panelHistoryIndex] = true;
	engine().zIndex[panelHistoryIndex] = 1e4;
}

function destroyDebugPanel() {
	if (panelBoxIndex >= 0) {
		engine().releaseIndex("debug-panel-box");
		panelBoxIndex = -1;
	}

	if (panelTitleIndex >= 0) {
		engine().releaseIndex("debug-panel-title");
		panelTitleIndex = -1;
	}

	if (panelKeyIndex >= 0) {
		engine().releaseIndex("debug-panel-key");
		panelKeyIndex = -1;
	}

	if (panelFocusIndex >= 0) {
		engine().releaseIndex("debug-panel-focus");
		panelFocusIndex = -1;
	}

	if (panelStatsIndex >= 0) {
		engine().releaseIndex("debug-panel-stats");
		panelStatsIndex = -1;
	}

	if (panelHistoryIndex >= 0) {
		engine().releaseIndex("debug-panel-history");
		panelHistoryIndex = -1;
	}
}

export function getDebugPanel() {
	return () => ({
		visible: $.get(debugVisible),
		toggle: toggleDebugPanel,
		updateKey: updateDebugKey,
		lastKey: $.get(lastKey),
		lastRawKey: $.get(lastRawKey),
		keyHistory: $.get(keyHistory)
	});
}