/* bindable-prop.svelte.ts generated by Svelte v5.38.7 */
import * as $ from 'svelte/internal/client';

export function createBindable(options) {
	let value = $.tag($.state($.proxy(options.initial)), 'value');

	return {
		get value() {
			return $.get(value);
		},

		set value(newValue) {
			const transformedValue = options.transform ? options.transform(newValue) : newValue;

			if (options.validate && !options.validate(transformedValue)) {
				return;
			}

			$.set(value, transformedValue, true);
			options.onChange?.(transformedValue);
		},

		get blessedValue() {
			return options.toBlessedTransform
				? options.toBlessedTransform($.get(value))
				: $.get(value);
		},

		updateFromBlessed(blessedValue) {
			this.value = options.transform ? options.transform(blessedValue) : blessedValue;
		}
	};
}

export const BindablePresets = {
	string(initial = "", maxLength) {
		return {
			initial,
			transform: (value) => String(value),
			validate: maxLength ? (value) => value.length <= maxLength : undefined
		};
	},

	boolean(initial = false) {
		return { initial, transform: (value) => Boolean(value) };
	},

	number(initial = 0, min, max) {
		return {
			initial,

			transform: (value) => {
				const num = Number(value);

				if (isNaN(num)) return initial;
				if ($.strict_equals(min, undefined, false) && num < min) return min;
				if ($.strict_equals(max, undefined, false) && num > max) return max;

				return num;
			}
		};
	},

	index(initial = 0, itemCount = 0) {
		return {
			initial,

			transform: (value) => {
				const num = Number(value);

				if (isNaN(num)) return initial;

				return Math.max(0, Math.min(itemCount - 1, num));
			}
		};
	}
};

export function bindable(initial, options) {
	return createBindable({ initial, ...options });
}