/* style-state.svelte.ts generated by Svelte v5.38.7 */
import * as $ from 'svelte/internal/client';

export class StyleState {
	#isHovered = $.tag($.state(false), 'StyleState.isHovered');

	get isHovered() {
		return $.get(this.#isHovered);
	}

	set isHovered(value) {
		$.set(this.#isHovered, value, true);
	}

	#isFocused = $.tag($.state(false), 'StyleState.isFocused');

	get isFocused() {
		return $.get(this.#isFocused);
	}

	set isFocused(value) {
		$.set(this.#isFocused, value, true);
	}

	#isPressed = $.tag($.state(false), 'StyleState.isPressed');

	get isPressed() {
		return $.get(this.#isPressed);
	}

	set isPressed(value) {
		$.set(this.#isPressed, value, true);
	}

	normalStyle;
	hoverStyle;
	focusStyle;
	pressedStyle;
	inherit;
	parent;

	constructor(config = {}) {
		this.normalStyle = config.normal || {};
		this.hoverStyle = config.hover || {};
		this.focusStyle = config.focus || {};
		this.pressedStyle = config.pressed || {};
		this.inherit = config.inherit ?? true;
		this.parent = config.parent;
	}

	#currentStyle = $.tag(
		$.derived(() => {
			let style = this.getBaseStyle();

			if (this.isHovered) {
				style = this.mergeStyles(style, this.hoverStyle);
			}

			if (this.isFocused) {
				style = this.mergeStyles(style, this.focusStyle);
			}

			if (this.isPressed) {
				style = this.mergeStyles(style, this.pressedStyle);
			}

			return style;
		}),
		'StyleState.currentStyle'
	);

	get currentStyle() {
		return $.get(this.#currentStyle);
	}

	set currentStyle(value) {
		$.set(this.#currentStyle, value);
	}

	#blessedStyle = $.tag(
		$.derived(() => {
			const style = this.currentStyle;
			const blessed = {};

			if (style.fg) blessed.fg = style.fg;
			if (style.bg) blessed.bg = style.bg;
			if (style.bold) blessed.bold = style.bold;
			if (style.underline) blessed.underline = style.underline;
			if (style.blink) blessed.blink = style.blink;
			if (style.inverse) blessed.inverse = style.inverse;
			if (style.invisible) blessed.invisible = style.invisible;
			if (style.italic) blessed.italic = style.italic;
			if (style.border) blessed.border = { ...style.border };
			if (style.scrollbar) blessed.scrollbar = { ...style.scrollbar };
			if (style.label) blessed.label = { ...style.label };
			if (style.focus) blessed.focus = this.convertToBlessedStyle(style.focus);
			if (style.hover) blessed.hover = this.convertToBlessedStyle(style.hover);

			return blessed;
		}),
		'StyleState.blessedStyle'
	);

	get blessedStyle() {
		return $.get(this.#blessedStyle);
	}

	set blessedStyle(value) {
		$.set(this.#blessedStyle, value);
	}

	setHovered(value) {
		this.isHovered = value;
	}

	setFocused(value) {
		this.isFocused = value;
	}

	setPressed(value) {
		this.isPressed = value;
	}

	updateNormalStyle(style) {
		this.normalStyle = this.mergeStyles(this.normalStyle, style);
	}

	updateHoverStyle(style) {
		this.hoverStyle = this.mergeStyles(this.hoverStyle, style);
	}

	updateFocusStyle(style) {
		this.focusStyle = this.mergeStyles(this.focusStyle, style);
	}

	updatePressedStyle(style) {
		this.pressedStyle = this.mergeStyles(this.pressedStyle, style);
	}

	setParent(parent) {
		this.parent = parent;
	}

	getBaseStyle() {
		let style = { ...this.normalStyle };

		if (this.inherit && this.parent) {
			const parentStyle = this.parent.currentStyle;

			style = this.mergeStyles(parentStyle, style);
		}

		return style;
	}

	mergeStyles(base, override) {
		if (!override) return { ...base };

		const merged = { ...base };

		Object.keys(override).forEach((key) => {
			const value = override[key];

			if ($.strict_equals(value, undefined, false) && $.strict_equals(typeof value, "object", false)) {
				merged[key] = value;
			}
		});

		if (override.border) {
			merged.border = { ...base.border, ...override.border };
		}

		if (override.scrollbar) {
			merged.scrollbar = {
				...base.scrollbar,
				...override.scrollbar,

				track: override.scrollbar.track
					? { ...base.scrollbar?.track, ...override.scrollbar.track }
					: base.scrollbar?.track
			};
		}

		if (override.label) {
			merged.label = { ...base.label, ...override.label };
		}

		return merged;
	}

	convertToBlessedStyle(style) {
		const blessed = {};

		if (style.fg) blessed.fg = style.fg;
		if (style.bg) blessed.bg = style.bg;
		if ($.strict_equals(style.bold, undefined, false)) blessed.bold = style.bold;
		if ($.strict_equals(style.underline, undefined, false)) blessed.underline = style.underline;
		if ($.strict_equals(style.blink, undefined, false)) blessed.blink = style.blink;
		if ($.strict_equals(style.inverse, undefined, false)) blessed.inverse = style.inverse;
		if ($.strict_equals(style.invisible, undefined, false)) blessed.invisible = style.invisible;
		if ($.strict_equals(style.italic, undefined, false)) blessed.italic = style.italic;

		return blessed;
	}
}

export function createStyleState(config) {
	return new StyleState({
		normal: { fg: "white", bg: "black", ...config?.normal },
		hover: { bg: "gray", ...config?.hover },
		focus: { border: { fg: "cyan" }, ...config?.focus },
		pressed: { bg: "blue", fg: "white", ...config?.pressed },
		...config
	});
}

export function useStyleStateEvents(element, styleState) {
	element.on("mouseover", () => styleState.setHovered(true));
	element.on("mouseout", () => styleState.setHovered(false));
	element.on("mousedown", () => styleState.setPressed(true));
	element.on("mouseup", () => styleState.setPressed(false));
	element.on("focus", () => styleState.setFocused(true));
	element.on("blur", () => styleState.setFocused(false));

	return () => {
		element.removeAllListeners("mouseover");
		element.removeAllListeners("mouseout");
		element.removeAllListeners("mousedown");
		element.removeAllListeners("mouseup");
		element.removeAllListeners("focus");
		element.removeAllListeners("blur");
	};
}