/* mount.svelte.ts generated by Svelte v5.38.7 */
import * as $ from 'svelte/internal/client';
import { terminalSize, setTerminalSize } from './core/state/engine.svelte.js';
import { initializeSimpleLayout } from './core/layout/layout-simple.svelte.js';
import { initializeRenderer } from './core/render/renderer.svelte.js';
import { keyboard } from './input/keyboard.svelte.js';
import * as ANSI from './utils/ansi-codes.mjs';

export function mount(rootComponent, options = {}) {
	const cols = process.stdout.columns || 80;
	const rows = process.stdout.rows || 24;

	setTerminalSize(cols, rows);
	terminalSize.fullscreen = options.fullscreen || false;

	if (options.fullscreen) {
		process.stdout.write(ANSI.ENTER_ALT_SCREEN);
		process.stdout.write(ANSI.CLEAR_SCREEN);
	}

	process.stdout.write(ANSI.HIDE_CURSOR);
	process.stdout.write(ANSI.ENABLE_MOUSE);
	keyboard.initialize();
	keyboard.onKey("Tab", () => keyboard.focusNext());
	keyboard.onKey("Shift+Tab", () => keyboard.focusPrevious());
	keyboard.onKey("Escape", () => keyboard.clearFocus());

	const handleError = (error) => {
		if (options?.fullscreen) {
			process.stdout.write(ANSI.EXIT_ALT_SCREEN);
		}

		process.stdout.write(ANSI.SHOW_CURSOR);
		process.stdout.write(ANSI.CLEAR_SCREEN);
		process.stdout.write(ANSI.DISABLE_MOUSE);
		process.stdout.write(ANSI.RESET);
		console.clear();

		console.error(`\x1B[41m\x1B[37m\x1B[1m SVELTUI RUNTIME ERROR \x1B[0m
`);

		console.error("\x1B[31m\x1B[1mError:\x1B[0m \x1B[37m" + error.message + `\x1B[0m
`);

		if (error.stack) {
			console.error("\x1B[33m\x1B[1mStack Trace:\x1B[0m");

			const stackLines = error.stack.split(`
`).slice(1);

			stackLines.forEach((line) => {
				if (line.includes("node_modules")) {
					console.error("\x1B[90m" + line + "\x1B[0m");
				} else if (line.includes("at ")) {
					console.error("\x1B[36m" + line + "\x1B[0m");
				} else {
					console.error(...$.log_if_contains_state('error', line));
				}
			});
		}

		console.error(`
\x1B[33m\uD83D\uDCA1 Tips:\x1B[0m`);

		console.error("  • Check that all components are imported correctly");
		console.error("  • Ensure Happy DOM is registered before Svelte imports");
		console.error("  • Verify you're using Svelte 5 rune syntax");

		console.error(`
─`.repeat(60) + `
`);

		process.exit(1);
	};

	process.on("uncaughtException", handleError);
	process.on("unhandledRejection", handleError);

	const effectCleanup = $.effect_root(() => {
		const layoutCleanup = initializeSimpleLayout();
		const rendererCleanup = initializeRenderer();

		rootComponent();

		const handleResize = () => {
			const newCols = process.stdout.columns || 80;
			const newRows = process.stdout.rows || 24;

			setTerminalSize(newCols, newRows);
		};

		process.stdout.on("resize", handleResize);

		return () => {
			process.stdout.off("resize", handleResize);
			process.off("SIGINT", handleExit);
			process.off("SIGTERM", handleExit);
			process.off("uncaughtException", handleError);
			process.off("unhandledRejection", handleError);
			rendererCleanup();
			layoutCleanup();
		};
	});

	const cleanup = () => {
		effectCleanup();
		keyboard.cleanup();
		process.stdout.write(ANSI.DISABLE_MOUSE);

		if (options.fullscreen) {
			process.stdout.write(ANSI.EXIT_ALT_SCREEN);
		}

		process.stdout.write(ANSI.SHOW_CURSOR);
		process.stdout.write(ANSI.RESET);
	};

	const handleExit = () => {
		cleanup();
		process.exit(0);
	};

	process.on("SIGINT", handleExit);
	process.on("SIGTERM", handleExit);

	return { cleanup, unmount: cleanup };
}